### ISSUE TITLE
DFB-Branch in den Master mergen

### ISSUE THREAD

**Issue by luniki** [virtUOS/courseware#8]
Der dfb32-Branch enthält viele Features, die so oder in abgewandelter Form auch in den master-Branch gehören.

**Comment by luniki** [comment]
Die gegenwärtige Liste der zu mergenden Commits:

**Comment by luniki** [comment]
- [ ] 3b6b7b8 use PluginEngine to check for existence of VipsPlugin
- [ ] ebb22f2 hide list numbering of sub/chapters etc.
- [ ] 23b1fd7 use variables in section.less
- [ ] 83d033a fix block adding
- [ ] d61b2c6 non dfb style for new elements
- [ ] 6a0c08e fix darn SORMCollection#map
- [ ] 2808764 get Plugin
- [ ] a41dffd another hack
- [ ] bc8a78f TestBlock hack at line 96
- [ ] 65fa25c "Diskussion" statt "Kommentare" für Einzeldiskussion
- [ ] 586aa1c Right border was cut off in some contexts
- [ ] fbd9cdc fix expand/collapse
- [ ] c26e715 implement non-grouped discussions
- [ ] 131c019 differentiate two types of discussion
- [ ] a4c8da5 do not expand/collapse outside of a contentbox
- [ ] 311d0bc expand and collapse discussions
- [ ] cd19a89 Left border was cut off in some contexts
- [ ] 5e2ee8c sort discussions by depth-first tree traversal
- [ ] 422617c on profile page show discussions with lecturers in courses with activated courseware
- [ ] a3a39a2 rename .writer to .comment-writer, fixes dfb#336
- [ ] 3c3aee0 open threads via JS
- [ ] 80e1a7c fix navigation for tutor and up
- [ ] fb06861 differentiate between profile's content boxes
- [ ] d3ae3cb show lecturer discussion for authors
- [ ] aed734e Nutzerbilder in Progress-Übersicht und korrekter Hintergrund
- [ ] ff92e6f change to tutor
- [ ] 283fa96 add homepage contentbox
- [ ] b483b8e Merge branch 'master' of https://github.com/virtUOS/courseware
- [ ] 486655b fix fatal error of blubber blocks
- [ ] 11de186 refs dfb#320
- [ ] 98a9a49 fix wrong type when adding block in section
- [ ] 0c4d65d do not double include mooc-progress
- [ ] 9495e85 refine postRender js in order to allow fileuploads refs dfb#315
- [ ] ef52114 Hinweis, wenn alle Fragen richtig beantwortet wurden Bufix: Darstellung Lückentext-Lösungen closes #316
- [ ] d0c0da0 add css classes to TestBlock
- [ ] 522149a fix dfb#321
- [ ] 044da7d fix darn SORM #map problem when using mustache
- [ ] 6026e96 use self instead of this
- [ ] 0ac604c change "Diskussion" to "Gruppendiskussion", fixes dfb#323
- [ ] 7646977 fix double postRendering
- [ ] 5280db9 - TestBlock-Wiederholung wieder eingebaut - Progress-View zeigt für dozent Fortschritt aller Teilnehmer - Discussion in Progress-View eingebaut
- [ ] 0d9ae45 reinsert file navigation item to make wysiwyg-upload work
- [ ] 738233a remove navigation items (members, files, blubberforum and vips for students) hack in line 213 has to be solved correctly
- [ ] 60e4cb6 show correct exercise after submission
- [ ] c87ee04 dirty fix: no $sub ; no hasUserCompleted
- [ ] e05724a change VideoBlock iframe height
- [ ] 0cd9af8 style discussions page
- [ ] 6e7448d fix TestBlock navigation
- [ ] 2768214 TestBlock bugfix
- [ ] dcea169 change Testblock: display only one question, back and next buttons for further questions YET NO CSS MODIFICATIONS
- [ ] 1911cc3 Bugfix: Missing ) in template
- [ ] 65703e7 activate sidebar blocks
- [ ] 563cab5 add unstyled Kurskommunikation
- [ ] d738391 Selbsttests wiederholen bis korrekt, refs #2
- [ ] 98d5527 add sidebar widgets
- [ ] 50b210b cleanup DiscussionBlock
- [ ] 7e89783 use initializeFromDOM
- [ ] 13d5fd7 delay init from DOM until there is actual content
- [ ] cde0236 Chrome compatibility issue
- [ ] 8499cb7 Add dfb.tv video source
- [ ] ebe3750 Update README.md
- [ ] 8f00baa add DiscussionBlock
- [ ] 82aab39 use current version of underscore instead of the core one
- [ ] 7cf6d95 update backbone to 1.2.0
- [ ] b145ad4 add DiscussionBlock's scaffolding, refs dfb#279
- [ ] 3e3dab7 rename BlubberBlock's descriptive name to Blubber
- [ ] d6ffd61 hide section from students in seq progression
- [ ] 84c61a2 only show pub date if there is one
- [ ] 2c8fb28 add courseware's settings page and progression
- [ ] 1d16b2b use current_courseware's title in navigation
- [ ] fcff198 use current_courseware service
- [ ] 17525b9 define service to retrieve current courseware
- [ ] c7db188 change default title of coursewares
- [ ] f5f0997 add 1st version of ConfirmBlock
- [ ] 4327168 send blocks' grades back
- [ ] 0124d36 add type of view to block components

**Comment by luniki** [comment]
Ich habe jetzt alle commits klassifiziert in folgende Kategorien:

A. commits, die auf jeden Fall in den master wandern
B. commits, die zu Features gehören, die nur angepasst in den master gemerged werden können
C. commits, die nur für den DFB von Interesse sind

Danach habe ich alle commits der Kategorie A in den master wandern lassen: siehe b075b50...667c27a

Die commits der Kategorien B und C habe ich auseinander sortiert und für jedes Feature einen entsprechenden Feature-Branch aufgemacht.

**Comment by luniki** [comment]
Folgende Feature-Branches sind jetzt vorhanden:

* Seitenblöcke: https://github.com/virtUOS/courseware/compare/master...asidesection 
* Gruppendiskussions/Kommentarblock: https://github.com/virtUOS/courseware/compare/master...discussionblock
* Seite "Kommunikation im Kurs": https://github.com/virtUOS/courseware/compare/master...discussion-overview
* Fortschrittseite: Kommunikation TN mit Referent: https://github.com/virtUOS/courseware/compare/master...communication-on-progress-page
* Profil: Kommunikation TN mit Referent: https://github.com/virtUOS/courseware/compare/master...course-com-on-profile
* DFB-Videos: https://github.com/virtUOS/courseware/compare/master...dfbvideotype
* verschiedene kleine Hacks: https://github.com/virtUOS/courseware/compare/master...misc-hacks

Diese Feature-Branches müssen in die Kategorien einsortiert werden. Ggfs müssen diese Features angepasst werden, damit sie auch in anderen Kontexten Sinn machen. (Beispiel: Seitenblöcke nur nach entsprechender Konfiguration aktiviert)

**Comment by luniki** [comment]
@tthelen Kannst du die Kategorisierung vornehmen und falls erforderlich aufschreiben, wie das jeweilige Feature angepasst werden soll, damit es auch allgemein genutzt werden kann?

**Comment by tthelen** [comment]
Wenn du mir sagst, wie das geht... Was für Kategorien? Wo finde ich die?
